# Generated by Django 4.0.1 on 2022-12-12 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offlineWatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snack',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.cinema'),
        ),
        migrations.AddField(
            model_name='show',
            name='Movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.movie'),
        ),
        migrations.AddField(
            model_name='show',
            name='cinemaHall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.cinemahall'),
        ),
        migrations.AddField(
            model_name='sessionseat',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionseat_row', to='offlineWatch.sessionrow'),
        ),
        migrations.AddField(
            model_name='sessionseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.seat'),
        ),
        migrations.AddField(
            model_name='sessionseat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.session'),
        ),
        migrations.AddField(
            model_name='sessionrow',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.row'),
        ),
        migrations.AddField(
            model_name='sessionrow',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='cinemahall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='offlineWatch.cinemahall'),
        ),
        migrations.AddField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.movie'),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_seat', to='offlineWatch.row'),
        ),
        migrations.AddField(
            model_name='row',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_row', to='offlineWatch.cinemahall'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='offlineWatch.cinema'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.address'),
        ),
        migrations.AddField(
            model_name='boughtsnack',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offlineWatch.snack'),
        ),
        migrations.AddField(
            model_name='boughtsnack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL),
        ),
    ]
