# Generated by Django 4.0.1 on 2022-12-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('days_to_update', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('C', 'Comment'), ('R', 'Review')], max_length=1)),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('ST', 'Standard'), ('PR', 'Premium')], default='ST', max_length=2)),
                ('price', models.IntegerField()),
                ('quality', models.CharField(max_length=120)),
                ('download_speed', models.CharField(max_length=120)),
                ('days', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('video', models.TextField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineWatch.season')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('poster', models.TextField(default='')),
                ('trailer', models.TextField()),
                ('premier', models.TextField()),
                ('release_date', models.DateField()),
                ('length', models.IntegerField()),
                ('cast', models.TextField()),
                ('ageLimit', models.TextField()),
                ('producer', models.TextField()),
                ('language', models.TextField()),
                ('country', models.TextField()),
                ('genre_list', models.ManyToManyField(related_name='serial_genre_list', to='onlineWatch.Genre')),
                ('main_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_main_genre', to='onlineWatch.genre')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineWatch.serial'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.TextField()),
                ('poster', models.TextField(default='')),
                ('trailer', models.TextField()),
                ('premier', models.TextField()),
                ('release_date', models.DateField()),
                ('length', models.IntegerField()),
                ('cast', models.TextField()),
                ('ageLimit', models.TextField()),
                ('producer', models.TextField()),
                ('language', models.TextField()),
                ('country', models.TextField()),
                ('genre_list', models.ManyToManyField(related_name='film_genre_list', to='onlineWatch.Genre')),
                ('main_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_main_genre', to='onlineWatch.genre')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('C', 'Comment'), ('R', 'Review')], max_length=1)),
                ('comment_text', models.TextField()),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_comment', to='onlineWatch.serial')),
            ],
        ),
    ]
