# Generated by Django 4.0.1 on 2022-11-25 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('video', models.TextField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineWatch.season')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('poster', models.TextField(default='')),
                ('trailer', models.TextField()),
                ('premier', models.TextField()),
                ('release_date', models.DateField()),
                ('length', models.IntegerField()),
                ('cast', models.TextField()),
                ('ageLimit', models.TextField()),
                ('producer', models.TextField()),
                ('language', models.TextField()),
                ('country', models.TextField()),
                ('main_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineWatch.genre')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineWatch.serial'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.TextField()),
                ('poster', models.TextField(default='')),
                ('trailer', models.TextField()),
                ('premier', models.TextField()),
                ('release_date', models.DateField()),
                ('length', models.IntegerField()),
                ('cast', models.TextField()),
                ('ageLimit', models.TextField()),
                ('producer', models.TextField()),
                ('language', models.TextField()),
                ('country', models.TextField()),
                ('main_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_genre', to='onlineWatch.genre')),
            ],
        ),
    ]
