# Generated by Django 4.0.1 on 2022-11-25 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineWatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre_list',
            field=models.ManyToManyField(related_name='film_genre_list', to='onlineWatch.Genre'),
        ),
        migrations.AddField(
            model_name='serial',
            name='genre_list',
            field=models.ManyToManyField(related_name='serial_genre_list', to='onlineWatch.Genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='main_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_main_genre', to='onlineWatch.genre'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='main_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_main_genre', to='onlineWatch.genre'),
        ),
    ]
