# Generated by Django 4.1.2 on 2022-11-30 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineWatch', '0002_film_genre_list_serial_genre_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('ST', 'Standard'), ('PR', 'Premium')], default='ST', max_length=2)),
                ('price', models.IntegerField()),
                ('quality', models.CharField(max_length=120)),
                ('download_speed', models.CharField(max_length=120)),
                ('days', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('days_to_update', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='onlineWatch.subscription')),
            ],
        ),
    ]
