# Generated by Django 4.1.2 on 2022-11-30 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineWatch', '0002_film_genre_list_serial_genre_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('C', 'Comment'), ('R', 'Review')], max_length=1)),
                ('comment_text', models.TextField()),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineWatch.serial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('C', 'Comment'), ('R', 'Review')], max_length=1)),
                ('comment_text', models.TextField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineWatch.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
