# Generated by Django 4.0.1 on 2022-12-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineWatch', '0003_commentsserial_commentsfilm'),
        ('onlineWatch', '0003_subscription_clientsubscription'),
    ]

    operations = [
    ]
