# Generated by Django 4.0.1 on 2022-12-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineWatch', '0004_merge_20221202_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsfilm',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_comment', to='onlineWatch.film'),
        ),
        migrations.AlterField(
            model_name='commentsserial',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_comment', to='onlineWatch.serial'),
        ),
    ]
