# Generated by Django 4.1.2 on 2022-11-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_stripe_id_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('MA', 'Main admin'), ('RG', 'Regular'), ('CA', 'Cinema admin'), ('RC', 'Recensor')], default='RG', max_length=2),
        ),
    ]
