# Generated by Django 4.0.1 on 2022-12-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_seat_hall_row_alter_seat_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='users.row')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.session')),
            ],
        ),
    ]
