# Generated by Django 4.0.1 on 2022-12-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sessionrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionseat',
            name='row',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.sessionrow'),
            preserve_default=False,
        ),
    ]
